# Memory Allocation to prevent Out Of Memory crashes in GitHub Actions
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Disable Daemon for CI environments
org.gradle.daemon=false

# Enable Parallel Builds and Caching
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX and Jetifier support
android.useAndroidX=true
android.enableJetifier=true

# Kotlin Code Style
kotlin.code.style=official
